name: voicebit-index-dev

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches:
      - main

  # Allow manual trigger
  workflow_dispatch:

jobs:
  voicebit-index-dev-deploy:
    runs-on: ubuntu-latest
    environment: dev
    permissions:
      id-token: write #This is required for requesting the OIDC JWT Token
      contents: read #Required when GH token is used to authenticate with private repo

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2
        with:
          lfs: true

      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Deploy voicebit-index
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }}
          dockerfilePath: Dockerfile
          registryUrl: voicebitacrwestus2.azurecr.io
          registryUsername: ${{ secrets.ACR_USERNAME }}
          registryPassword: ${{ secrets.ACR_PASSWORD }}
          containerAppName: voicebit-index-dev
          containerAppEnvironment: voicebit-env-dev-westus2
          resourceGroup: voicebit-rg-dev-westus2
          imageToBuild: voicebitacrwestus2.azurecr.io/voicebit-index-dev:${{ github.sha }}
          environmentVariables: >
            "ENVIRONMENT=dev" 